#!/usr/bin/env python3
"""Barcode-design statistics for the Barcode contract section (design_numbers.tex).

Reads the slide oligo lists (extracted from the Visium HD slide-design file
distributed with Space Ranger 4.1.0) and our read-space contract summary,
which records the Read 1 segments listed in the chemistry definition and the
collisions of that fixed-segment representation. Prints LaTeX macros.
"""
import json
import sys

OLIGOS = "<storage>/runs/cleanroom_hd_mouse_brain/slide_oligos"
CONTRACT = ("<datasets>/visium_hd_human_crc/hd_barcode_contract/"
            "visium_hd_v1_readspace_suffix_prefix_20260504/summary.json")

halves = {h: [l.strip() for l in open(f"{OLIGOS}/{h}_full_oligos.txt") if l.strip()] for h in ("bc1", "bc2")}
out = {}
for h, ol in halves.items():
    lens = [len(o) for o in ol]
    if any(lens[i] == lens[i + 1] for i in range(len(lens) - 1)):
        sys.exit(f"{h}: lengths do not alternate between neighbours")
    index = {o: i for i, o in enumerate(ol)}
    nested = [(i, index[o[1:]]) for i, o in enumerate(ol) if o[1:] in index]
    nested += [(i, index[o[:-1]]) for i, o in enumerate(ol) if o[:-1] in index]
    if any(abs(i - j) != 1 for i, j in nested):
        sys.exit(f"{h}: a nested pair is not adjacent")
    out[h] = len(nested)

c = json.load(open(CONTRACT))
seg = {s["part"]: s for s in c["chemistry"]["segments"]}
st = c["contract_stats"]
macros = {
    "designBCOneMinLength": min(map(len, halves["bc1"])),
    "designBCOneMaxLength": max(map(len, halves["bc1"])),
    "designBCTwoMinLength": min(map(len, halves["bc2"])),
    "designBCTwoMaxLength": max(map(len, halves["bc2"])),
    "designBarcodeMinLength": sum(min(map(len, halves[h])) for h in halves),
    "designBarcodeMaxLength": sum(max(map(len, halves[h])) for h in halves),
    "chemCombinedSegmentLength": sum(s["length"] for s in seg.values()),
    "chemSegmentLength": seg["bc1"]["length"],
    "chemBCOneOffset": seg["bc1"]["offset"],
    "chemBCTwoOffset": seg["bc2"]["offset"],
    "chemOffsetLo": c["chemistry"]["min_offset"],
    "chemOffsetHi": c["chemistry"]["max_offset"],
    "designNestedBCOnePairs": out["bc1"],
    "designNestedBCTwoPairs": out["bc2"],
    "segBCOneShared": st["bc1_segment_uniqueness"]["colliding_segments"],
    "segBCOneMaxShare": st["bc1_segment_uniqueness"]["max_collision"],
    "segKeysAmbiguous": f'{st["raw28_ambiguous_keys"]:,}',
    "segKeysDistinct": f'{st["raw28_distinct"]:,}',
}
if seg["bc2"]["length"] != seg["bc1"]["length"]:
    sys.exit("segment lengths differ")
print("% Generated by figures/scripts/barcode_design_stats.py. Sources: slide oligo lists")
print(f"% {OLIGOS} (from the slide-design file distributed with Space Ranger 4.1.0)")
print(f"% and the read-space contract summary {CONTRACT}.")
print("% Not yet part of the sealed number export; move into it before submission.")
for k, v in macros.items():
    print(f"\\newcommand{{\\{k}}}{{{v}}}")
