#!/usr/bin/env python3
"""Cited release and its reproduction of the official spatial gates (release_numbers.tex).

Reads the provenance record of the v1.9.5.a rerun of the four official spatial
100K gates and the release metadata shipped inside the release asset.
"""
import json
import sys

RECORD = sys.argv[1] if len(sys.argv) > 1 else (
    "<local>/runs/visium_hd_publication/"
    "20260927_v195a_spatial_gate_rerun/results/spatial_gate_rerun_v195a.json")
record = json.load(open(RECORD))
meta = dict(line.split("=", 1) for line in record["release_metadata"].splitlines() if "=" in line)
cases = record["cases"].values()
if record["status"] != "complete" or not record["all_pass"]:
    raise SystemExit("the gate rerun did not pass")
identical = sum(c["identical"] for c in cases)
components = sum(c["components"] for c in cases)
if identical != components:
    raise SystemExit("not every MEX file is identical")
print(f"% Generated by figures/scripts/release_gate_numbers.py from {RECORD}")
print(f"\\newcommand{{\\citedRelease}}{{{meta['VERSION']}}}")
print(f"\\newcommand{{\\citedReleaseCommit}}{{{meta['COMMIT_SHA']}}}")
print(f"\\newcommand{{\\releaseGateCases}}{{{['zero','one','two','three','four','five'][len(record['cases'])]}}}")
print(f"\\newcommand{{\\releaseGateFiles}}{{{components}}}")
