#!/usr/bin/env python3
"""How often Space Ranger's emitted square exceeds two edits per half (audit_limit_numbers.tex).

On slide H1-VM2JXXK/A1, every shared-eligible read either has a square within
two edits per half (a candidate) or not. Space Ranger's square exceeds that
limit when (a) the read has no candidate but Space Ranger emitted a square, or
(b) Space Ranger's square is not a closest square and its best split needs more
than two edits in one half. (a) follows from the candidate-preservation counts,
(b) from the raw edit ledger, which also shows whether (b) falls in the
short-BC2 overlap geometry.
"""
import csv
import gzip
import json
from pathlib import Path

RUNS = "<runs>/runs"
CANDIDATES = f"{RUNS}/20260716_vm2jxxk_full_natural_candidate_reference_v1/candidate_preservation/summary.json"
TAXONOMY = f"{RUNS}/20260720_vm2jxxk_full_sr_disagreement_paper_taxonomy_v1/summary.json"
LEDGER = f"{RUNS}/20260720_vm2jxxk_full_sr_disagreement_raw_edit_audit_v1/nonminimum_raw_edit_ledger.tsv.gz"
LIMIT = 2
JOINT = (29, 31)          # joint barcode length: BC1 15-16 plus BC2 14-15 bases
MATES = Path(__file__).resolve().parents[1] / "data" / "sr_audit_no_candidate_mates.json"

counts = json.load(open(CANDIDATES))["counts"]
headline = json.load(open(TAXONOMY))["headline"]
eligible = counts["shared_eligible"]
emitted = eligible - counts["missing_sr_cb"]
emitted_with_candidate = headline["sr_selected_retained_minimum"] + headline["sr_selected_nonminimum"]
no_candidate_emitted = emitted - emitted_with_candidate
if headline["star_candidate_reads"] + headline["star_no_candidate_reads"] != eligible:
    raise SystemExit("candidate partition does not cover the shared-eligible reads")
if emitted_with_candidate + headline["sr_unassigned_with_star_candidate"] != headline["star_candidate_reads"]:
    raise SystemExit("candidate-read partition is inconsistent")

above = above_overlap = above_atypical = within = within_atypical = 0
with gzip.open(LEDGER, "rt") as handle:
    for row in csv.DictReader(handle, delimiter="\t"):
        atypical = not JOINT[0] <= len(row["raw_cr"]) <= JOINT[1]
        if max(int(row["sr_best_bc1_edit"]), int(row["sr_best_bc2_edit"])) > LIMIT:
            above += 1
            above_overlap += row["short_bc2_overlap"] == "1"
            above_atypical += atypical
        else:
            within += 1
            within_atypical += atypical
if above != headline["sr_raw_split_max_half_above_ed2"]:
    raise SystemExit("ledger disagrees with the taxonomy summary")
beyond = above + no_candidate_emitted
print("% Generated by figures/scripts/sr_audit_half_limit.py from the July 2026 audit of slide H1-VM2JXXK/A1")
print(f"\\newcommand{{\\auditSREmitted}}{{{emitted:,}}}")
print(f"\\newcommand{{\\auditSRNoCandidateEmitted}}{{{no_candidate_emitted:,}}}")
print(f"\\newcommand{{\\auditSRBeyondHalf}}{{{beyond:,}}}")
print(f"\\newcommand{{\\auditSRBeyondHalfPct}}{{{100 * beyond / emitted:.4f}}}")
print(f"\\newcommand{{\\auditSRAboveHalfInOverlap}}{{{above_overlap:,}}}")
mates = json.loads(MATES.read_text())
if mates["reads_with_square_but_no_candidate"] != no_candidate_emitted:
    raise SystemExit("molecule-mate record disagrees with the candidate counts")
print(f"\\newcommand{{\\auditJointLo}}{{{JOINT[0]}}}")
print(f"\\newcommand{{\\auditJointHi}}{{{JOINT[1]}}}")
print(f"\\newcommand{{\\auditAboveHalfAtypicalCR}}{{{above_atypical:,}}}")
print(f"\\newcommand{{\\auditWithinAtypicalCRPct}}{{{100 * within_atypical / within:.1f}}}")
print(f"\\newcommand{{\\auditNoCandidateMateSupported}}{{{mates['with_supporting_molecule_mate']:,}}}")
print(f"\\newcommand{{\\auditNoCandidateMateSupportedPct}}{{{100 * mates['with_supporting_molecule_mate'] / no_candidate_emitted:.1f}}}")
