#!/usr/bin/env python3
"""Provenance of the Space Ranger run audited in Results 4 (audit_numbers.tex).

Reads only the run's own records (_versions, _cmdline, outs/metrics_summary.csv),
never any pipeline source.
"""
import csv
import json
import os
import sys

RUN = sys.argv[1] if len(sys.argv) > 1 else "<runs>/20260716_vm2jxxk_natural_sr401_bam_v1"
version = json.load(open(f"{RUN}/_versions"))["pipelines"].split("-")[-1]
argv = open(f"{RUN}/_cmdline").read().split()
reference = os.path.basename(argv[argv.index("--transcriptome") + 1]).replace("refdata-gex-", "")
rows = list(csv.reader(open(f"{RUN}/outs/metrics_summary.csv")))
reads = int(float(dict(zip(rows[0], rows[1]))["Number of Reads"]))
print(f"% Generated by figures/scripts/sr_audit_provenance.py from {RUN}")
print(f"\\newcommand{{\\auditSRVersion}}{{{version}}}")
print(f"\\newcommand{{\\auditReference}}{{{reference}}}")
print(f"\\newcommand{{\\auditReadPairs}}{{{reads:,}}}")
