#!/usr/bin/env python3
"""Export Table 5 macros from the recorded worked cases, without repeating the audit."""
import csv
from pathlib import Path

source = Path(__file__).with_name("sr_audit_worked_cases.tsv")
with source.open() as handle:
    rows = list(csv.DictReader(handle, delimiter="\t"))
cases = list(dict.fromkeys(row["case"] for row in rows))
if len(cases) != 2 or len(rows) != 4:
    raise SystemExit("expected two recorded cases, each with closest and Space Ranger squares")

print("% Generated by figures/scripts/worked_case_numbers.py from sr_audit_worked_cases.tsv.")
for name, case in zip(("One", "Two"), cases):
    matches = {row["square"]: row for row in rows if row["case"] == case}
    if set(matches) != {"closest", "Space Ranger"}:
        raise SystemExit(f"unexpected squares in {case}")
    closest, vendor = matches["closest"], matches["Space Ranger"]
    if closest["split"] != vendor["split"]:
        raise SystemExit(f"different barcode splits in {case}")
    print(f"% {closest['read_id']}: {case}")
    for square, row in (("Closest", closest), ("SR", vendor)):
        for key, column in (("Row", "row"), ("Column", "col"),
                            ("BCOneEdits", "bc1_edits"), ("BCTwoEdits", "bc2_edits"),
                            ("TotalEdits", "total")):
            print(rf"\newcommand{{\case{name}{square}{key}}}{{{int(row[column])}}}")
